name: Claude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Moved from input to job level
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write # Required for OIDC authentication
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Or use OAuth token instead:
          # claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          claude_args: |
            --model claude-sonnet-4-5-20250929
            --allowedTools Read,Write,Edit,Glob,Grep,WebFetch,mcp__github,mcp__playwright,Bash(npm:*),Bash(git:*),Bash(exec:*),Bash(grep:*),Bash(bun:*),Bash(ls:*),Bash(node:*),Bash(cat:*),Bash(cd:*),Bash(cp:*),Bash(mv:*),Bash(mkdir:*),Bash(rm:*),Bash(curl:*)
            --mcp-config '{"mcpServers":{"github":{"command":"docker","args":["run","-i","--rm","-e","GITHUB_PERSONAL_ACCESS_TOKEN","ghcr.io/github/github-mcp-server:sha-7aced2b"],"env":{"GITHUB_PERSONAL_ACCESS_TOKEN":"${{ secrets.GITHUB_TOKEN }}"}},"playwright":{"command":"npx","args":["@playwright/mcp@latest"],"env":{"PLAYWRIGHT_EXTRA_HTTP_HEADERS":"{\"x-vercel-protection-bypass\":\"${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}\",\"x-vercel-set-bypass-cookie\":\"samesitenone\"}"}}}}'
          # Optional: Restrict network access to specific domains only
          # experimental_allowed_domains: |
          #   .anthropic.com
          #   .github.com
          #   api.github.com
          #   .githubusercontent.com
          #   bun.sh
          #   registry.npmjs.org
          #   .blob.core.windows.net
